---
- name: Install Prometheus Node Exporter
  hosts: all
  tasks:
    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt
        remote_src: yes

    - name: Create Node Exporter service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          [Service]
          ExecStart=/opt/node_exporter-1.3.1.linux-amd64/node_exporter
          [Install]
          WantedBy=default.target

    - name: Start and enable Node Exporter
      service:
        name: node_exporter
        state: started
        enabled: yes
